{
 "title": "Батерия",
 "time": { "from": "2021-10-06T21:00:00.000Z", "to": "now" },
 "panels": [
  {
   "title": "Средни стойности на батерията",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT \n  AVG(low_body_battery) AS low_avg\nFROM biathlon_training.body_battery"
    },
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT \n  AVG(high_body_battery) AS high_avg\nFROM biathlon_training.body_battery"
    }
   ]
  },
  {
   "title": "Енергиен баланс",
   "type": "barchart",
   "description": "Баланс между останалата наличната енергия на края на деня и нереализирания запас до 100% в началото на деня. ",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT \n  CAST(DATE_FORMAT(date, '%Y-%m-%d 00:00:00') AS DATE) AS day,\n  low_body_battery + high_body_battery - 105 AS balance\nFROM biathlon_training.body_battery\nWHERE date BETWEEN $__timeFrom() AND $__timeTo()\nORDER BY date DESC;"
    }
   ]
  },
  {
   "title": "Промяна",
   "type": "gauge",
   "description": "Среднен енергиен баланс през последните 3 дни в сравнение със предходните две седмици.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$last_3_days - $previous_2_weeks",
     "type": "math"
    }
   ]
  },
  {
   "title": "Най-ниска и най-висока стойност на батерията",
   "type": "timeseries",
   "description": "По ден (усреднена стойност за седмица)",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  CAST(DATE_FORMAT(date, '%Y-%m-%d 00:00:00') AS DATE) AS day,\n  ROUND(AVG(high_body_battery) OVER (ORDER BY date ROWS BETWEEN 7 PRECEDING AND CURRENT ROW), 0) AS smoothed_weight\nFROM\n  biathlon_training.body_battery\nORDER BY date ASC;"
    },
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  CAST(DATE_FORMAT(date, '%Y-%m-%d 00:00:00') AS DATE) AS day,\n  ROUND(AVG(low_body_battery) OVER (ORDER BY date ROWS BETWEEN 7 PRECEDING AND CURRENT ROW), 0) AS smoothed_weight\nFROM\n  biathlon_training.body_battery\nORDER BY date ASC;"
    },
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  CAST(DATE_FORMAT(date, '%Y-%m-%d 00:00:00') AS DATE) AS day,\n  ROUND(AVG(high_body_battery - low_body_battery) OVER (ORDER BY date ROWS BETWEEN 7 PRECEDING AND CURRENT ROW), 0) AS smoothed_weight\nFROM\n  biathlon_training.body_battery\nORDER BY date ASC;"
    }
   ]
  },
  {
   "title": "Брой дни с дадена минимална и максимална стойносто на батерията",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  high_body_battery\nFROM\n  biathlon_training.body_battery\nWHERE\n  date BETWEEN $__timeFrom() AND $__timeTo() AND \n  high_body_battery IS NOT NULL"
    },
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  low_body_battery\nFROM\n  biathlon_training.body_battery\nWHERE\n  date BETWEEN $__timeFrom() AND $__timeTo() AND \n  low_body_battery IS NOT NULL"
    }
   ]
  },
  {
   "title": "Енергиен баланс по година",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  DATE_FORMAT(date, '%Y') AS year,  -- Extract year and month from the date\n  AVG(low_body_battery + high_body_battery - 105) AS avg_balance\nFROM\n  biathlon_training.body_battery\nWHERE\n  date BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY year\nORDER BY year;"
    }
   ]
  },
  {
   "title": "Енергиен баланс по месец",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  DATE_FORMAT(date, '%m') AS month,\n  AVG(low_body_battery + high_body_battery - 105) AS avg_balance\nFROM\n  biathlon_training.body_battery\nWHERE\n  date BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY month\nORDER BY month;"
    }
   ]
  },
  {
   "title": "Брой дни с даден енергиен баланс",
   "type": "barchart",
   "description": "Колко дни съм бил с определен енергиен баланс",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  date,\n  ROUND((low_body_battery + high_body_battery - 105) / 10) * 10 AS balance\nFROM\n  biathlon_training.body_battery\nWHERE\n  date BETWEEN $__timeFrom() AND $__timeTo() AND \n  low_body_battery IS NOT NULL AND\n  high_body_battery IS NOT NULL\nORDER BY balance;"
    }
   ]
  }
 ]
}