{
 "title": "Калории",
 "time": { "from": "2021-10-06T21:00:00.000Z", "to": "now" },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT MIN(total_calories), date FROM biathlon_training.calories LIMIT 1 "
    },
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT MAX(total_calories), date FROM biathlon_training.calories LIMIT 1 "
    }
   ]
  },
  {
   "title": "Калории",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  CAST(DATE_FORMAT(date, '%Y-%m-%d 00:00:00') AS DATE) AS day,\n  ROUND(AVG(resting_calories) OVER (ORDER BY date ROWS BETWEEN 7 PRECEDING AND CURRENT ROW), 0) AS smoothed_resting_calories\nFROM\n  biathlon_training.calories\nORDER BY date ASC;"
    },
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  CAST(DATE_FORMAT(date, '%Y-%m-%d 00:00:00') AS DATE) AS day,\n  ROUND(AVG(active_calories) OVER (ORDER BY date ROWS BETWEEN 7 PRECEDING AND CURRENT ROW), 0) AS smoothed_active_calories\nFROM\n  biathlon_training.calories\nORDER BY date ASC;"
    }
   ]
  },
  {
   "title": "Промяна",
   "type": "gauge",
   "description": "Средни общи калории на ден през последата седмица в сравнение със предходните три седмици.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$last_7_days - $previous_3_weeks",
     "type": "math"
    }
   ]
  },
  {
   "title": "Средно дневно калории при активност по година",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  DATE_FORMAT(date, '%Y') AS year,\n  AVG(active_calories) AS avg_active_calories\nFROM\n  biathlon_training.calories\nWHERE\n  date BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY year\nORDER BY year;"
    }
   ]
  },
  {
   "title": "Средно дневно калории при активност по месец",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  DATE_FORMAT(date, '%m') AS month,\n  AVG(active_calories) AS avg_active_calories\nFROM\n  biathlon_training.calories\nWHERE\n  date BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY month\nORDER BY month;"
    }
   ]
  },
  {
   "title": "Брой дни с дадени калории при активност",
   "type": "barchart",
   "description": "Колко дни съм бил с определен и калории при активност",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  date,\n  ROUND(active_calories / 20) * 20 AS int_active_calories\nFROM\n  biathlon_training.calories\nWHERE\n  date BETWEEN $__timeFrom() AND $__timeTo() AND active_calories IS NOT NULL\nORDER BY int_active_calories;"
    }
   ]
  }
 ]
}