{
 "title": "Пулс",
 "time": { "from": "2021-10-06T21:00:00.000Z", "to": "now" },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT MIN(wellness_min_avg_hr), date FROM biathlon_training.heart_rate LIMIT 1 "
    },
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT MAX(wellness_max_avg_hr), date FROM biathlon_training.heart_rate LIMIT 1 "
    }
   ]
  },
  {
   "title": "Пулс (в покой)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT \n  CAST(DATE_FORMAT(date, '%Y-%m-%d 00:00:00') AS DATE) AS day,\n  resting_hr\nFROM biathlon_training.heart_rate\nORDER BY date DESC;"
    },
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  CAST(DATE_FORMAT(date, '%Y-%m-%d 00:00:00') AS DATE) AS day,\n  ROUND(AVG(resting_hr) OVER (ORDER BY date ROWS BETWEEN 7 PRECEDING AND CURRENT ROW), 0) AS smoothed_weight\nFROM\n  biathlon_training.heart_rate\nORDER BY date ASC;"
    }
   ]
  },
  {
   "title": "Промяна",
   "type": "gauge",
   "description": "Среднен пулс при покой през последните 3 дни в сравнение със предходните две седмици.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$last_3_days - $previous_2_weeks",
     "type": "math"
    }
   ]
  },
  {
   "title": "Минимален и максимален пулс",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  CAST(DATE_FORMAT(date, '%Y-%m-%d 00:00:00') AS DATE) AS day,\n  ROUND(AVG(wellness_max_avg_hr) OVER (ORDER BY date ROWS BETWEEN 7 PRECEDING AND CURRENT ROW), 0) AS smoothed_weight\nFROM\n  biathlon_training.heart_rate\nORDER BY date ASC;"
    },
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  CAST(DATE_FORMAT(date, '%Y-%m-%d 00:00:00') AS DATE) AS day,\n  ROUND(AVG(wellness_min_avg_hr) OVER (ORDER BY date ROWS BETWEEN 7 PRECEDING AND CURRENT ROW), 0) AS smoothed_weight\nFROM\n  biathlon_training.heart_rate\nORDER BY date ASC;"
    }
   ]
  },
  {
   "title": "Среден пулс в покой по година",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  DATE_FORMAT(date, '%Y') AS year,  -- Extract year and month from the date\n  AVG(resting_hr) AS avg_resting_hr              -- Calculate average weight for each month\nFROM\n  biathlon_training.heart_rate\nWHERE\n  date BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY year                           -- Group by the extracted month\nORDER BY year;"
    }
   ]
  },
  {
   "title": "Средeн пулс в покой по месец",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  DATE_FORMAT(date, '%m') AS month,\n  AVG(resting_hr) AS avg_resting_hr\nFROM\n  biathlon_training.heart_rate\nWHERE\n  date BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY month\nORDER BY month;"
    }
   ]
  },
  {
   "title": "Брой дни с даден пулс в покой",
   "type": "barchart",
   "description": "Колко дни съм бил с определен пулс в покой",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  date,\n  ROUND(resting_hr) AS int_resting_hr\nFROM\n  biathlon_training.heart_rate\nWHERE\n  date BETWEEN $__timeFrom() AND $__timeTo() AND resting_hr IS NOT NULL\nORDER BY int_resting_hr;"
    }
   ]
  }
 ]
}