{
 "title": "Сън",
 "time": { "from": "2021-10-06T21:00:00.000Z", "to": "now" },
 "panels": [
  {
   "title": "Средна сподължителност на съня",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  AVG(total_sleep_time) AS avg_overall_stress_level\nFROM biathlon_training.sleep \nWHERE \n  date BETWEEN $__timeFrom() AND $__timeTo()"
    }
   ]
  },
  {
   "title": "Време на заспиване и събуждане",
   "type": "timeseries",
   "description": "По ден (усреднено за 3 дни)",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  CAST(DATE_FORMAT(date, '%Y-%m-%d 00:00:00') AS DATE) AS day,\n  ROUND(AVG(sleep_start_seconds_to_midnight) OVER (ORDER BY date ROWS BETWEEN 3 PRECEDING AND CURRENT ROW), 0) AS smoothed_sleep_start_seconds_to_midnight\nFROM\n  biathlon_training.sleep\nORDER BY date ASC;"
    },
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  CAST(DATE_FORMAT(date, '%Y-%m-%d 00:00:00') AS DATE) AS day,\n  ROUND(AVG(sleep_end_seconds_to_midnight) OVER (ORDER BY date ROWS BETWEEN 3 PRECEDING AND CURRENT ROW), 0) AS smoothed_sleep_end_seconds_to_midnight\nFROM\n  biathlon_training.sleep\nORDER BY date ASC;"
    }
   ]
  },
  {
   "title": "Средна продължитеност на фазите",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT \n  AVG(light_time) AS low_avg\nFROM biathlon_training.sleep\nWHERE date BETWEEN $__timeFrom() AND $__timeTo()"
    },
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT \n  AVG(deep_time) AS medium_avg\nFROM biathlon_training.sleep\nWHERE date BETWEEN $__timeFrom() AND $__timeTo()"
    },
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT \n  AVG(rem_time) AS high_avg\nFROM biathlon_training.sleep\nWHERE date BETWEEN $__timeFrom() AND $__timeTo()"
    }
   ]
  },
  {
   "title": "Фази на съня",
   "type": "timeseries",
   "description": "По ден (усреднена стойност за седмица)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  CAST(DATE_FORMAT(date, '%Y-%m-%d 00:00:00') AS DATE) AS day,\n  ROUND(AVG(rem_time) OVER (ORDER BY date ROWS BETWEEN 7 PRECEDING AND CURRENT ROW), 0) AS smoothed_rem_time\nFROM\n  biathlon_training.sleep\nORDER BY date ASC;"
    },
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  CAST(DATE_FORMAT(date, '%Y-%m-%d 00:00:00') AS DATE) AS day,\n  ROUND(AVG(deep_time) OVER (ORDER BY date ROWS BETWEEN 7 PRECEDING AND CURRENT ROW), 0) AS smoothed_deep_time\nFROM\n  biathlon_training.sleep\nORDER BY date ASC;"
    },
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  CAST(DATE_FORMAT(date, '%Y-%m-%d 00:00:00') AS DATE) AS day,\n  ROUND(AVG(light_time) OVER (ORDER BY date ROWS BETWEEN 7 PRECEDING AND CURRENT ROW), 0) AS smoothed_light_time\nFROM\n  biathlon_training.sleep\nORDER BY date ASC;"
    }
   ]
  },
  {
   "title": "Среден заряд на батерията",
   "type": "stat",
   "description": "По време на сън",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  AVG(body_battery_change) AS avg_body_battery_change\nFROM biathlon_training.sleep \nWHERE \n  date BETWEEN $__timeFrom() AND $__timeTo()"
    }
   ]
  },
  {
   "title": "Зареждане на батерията по време на сън",
   "type": "timeseries",
   "description": "По ден (усреднена стойност за седмица)",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  CAST(DATE_FORMAT(date, '%Y-%m-%d 00:00:00') AS DATE) AS day,\n  ROUND(AVG(body_battery_change) OVER (ORDER BY date ROWS BETWEEN 7 PRECEDING AND CURRENT ROW), 0) AS smoothed_body_battery_change\nFROM\n  biathlon_training.sleep\nWHERE body_battery_change IS NOT NULL\nORDER BY date ASC;"
    }
   ]
  },
  {
   "title": "Дишане по време на сън",
   "type": "stat",
   "description": "Среден брой вдишвяния",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  respiration\nFROM biathlon_training.sleep \nWHERE \n  date BETWEEN $__timeFrom() AND $__timeTo()"
    }
   ]
  },
  {
   "title": "Качество на съня",
   "type": "timeseries",
   "description": "Промяна в заряда на батерията за час сън (по ден, усреднена стойност за седмица)",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  CAST(DATE_FORMAT(date, '%Y-%m-%d 00:00:00') AS DATE) AS day,\n  AVG(body_battery_change / (total_sleep_time / 3600)) OVER (ORDER BY date ROWS BETWEEN 7 PRECEDING AND CURRENT ROW) AS smoothed_body_battery_change_per_hour\nFROM\n  biathlon_training.sleep\nWHERE body_battery_change IS NOT NULL\nORDER BY date ASC;"
    }
   ]
  },
  {
   "title": "Средна продължителност на съня по година",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  DATE_FORMAT(date, '%Y') AS year,\n  AVG(total_sleep_time) AS avg_total_sleep_time\nFROM\n  biathlon_training.sleep\nWHERE\n  date BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY year\nORDER BY year;"
    }
   ]
  },
  {
   "title": "Средна продължителност на съня по месец",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  DATE_FORMAT(date, '%m') AS month,\n  AVG(total_sleep_time) AS avg_total_sleep_time\nFROM\n  biathlon_training.sleep\nWHERE\n  date BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY month\nORDER BY month;"
    }
   ]
  },
  {
   "title": "Брой дни с дадена продължителност на съня",
   "type": "barchart",
   "description": "Колко дни съм бил с определено ниво на стрес",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  date,\n  (ROUND(total_sleep_time / 600) * 600) AS rough_total_sleep_time\nFROM\n  biathlon_training.sleep\nWHERE\n  date BETWEEN $__timeFrom() AND $__timeTo() AND \n  total_sleep_time IS NOT NULL\nORDER BY rough_total_sleep_time;"
    }
   ]
  }
 ]
}