{
 "title": "Стъпки",
 "time": { "from": "2021-10-06T21:00:00.000Z", "to": "now" },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT MIN(total_steps), date FROM biathlon_training.steps LIMIT 1 "
    },
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT MAX(total_steps), date FROM biathlon_training.steps LIMIT 1 "
    }
   ]
  },
  {
   "title": "Стъпки",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT \n  CAST(DATE_FORMAT(date, '%Y-%m-%d 00:00:00') AS DATE) AS day,\n  total_steps\nFROM biathlon_training.steps\nORDER BY date DESC;"
    },
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  CAST(DATE_FORMAT(date, '%Y-%m-%d 00:00:00') AS DATE) AS day,\n  ROUND(AVG(total_steps) OVER (ORDER BY date ROWS BETWEEN 7 PRECEDING AND CURRENT ROW), 0) AS smoothed_weight\nFROM\n  biathlon_training.steps\nORDER BY date ASC;"
    }
   ]
  },
  {
   "title": "Промяна",
   "type": "gauge",
   "description": "Среден брой стъпки на ден през последата седмица в сравнение със предходните три седмици.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$last_7_days - $previous_3_weeks",
     "type": "math"
    }
   ]
  },
  {
   "title": "Среден дневен брой стъпки по година",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  DATE_FORMAT(date, '%Y') AS year,\n  AVG(total_steps) AS avg_total_steps\nFROM\n  biathlon_training.steps\nWHERE\n  date BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY year\nORDER BY year;"
    }
   ]
  },
  {
   "title": "Средeн дневен брой стъпки по месец",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  DATE_FORMAT(date, '%m') AS month,\n  AVG(total_steps) AS avg_total_steps\nFROM\n  biathlon_training.steps\nWHERE\n  date BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY month\nORDER BY month;"
    }
   ]
  },
  {
   "title": "Брой дни с даден брой стъпки",
   "type": "barchart",
   "description": "Колко дни съм бил с определен брой стъпки",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  date,\n  ROUND(total_steps / 1000) * 1000 AS int_total_steps\nFROM\n  biathlon_training.steps\nWHERE\n  date BETWEEN $__timeFrom() AND $__timeTo() AND total_steps IS NOT NULL\nORDER BY int_total_steps;"
    }
   ]
  }
 ]
}