{
 "title": "Стрес",
 "time": { "from": "2021-10-06T21:00:00.000Z", "to": "now" },
 "panels": [
  {
   "title": "Средно ниво на стрес",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  AVG(overall_stress_level) AS avg_overall_stress_level\nFROM biathlon_training.stress \nWHERE \n  date BETWEEN $__timeFrom() AND $__timeTo()"
    }
   ]
  },
  {
   "title": "Ниво на стрес",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  CAST(DATE_FORMAT(date, '%Y-%m-%d 00:00:00') AS DATE) AS day,\n  ROUND(AVG(overall_stress_level) OVER (ORDER BY date ROWS BETWEEN 7 PRECEDING AND CURRENT ROW), 0) AS smoothed_overall_stress_level\nFROM\n  biathlon_training.stress\nORDER BY date ASC;"
    },
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  CAST(DATE_FORMAT(date, '%Y-%m-%d 00:00:00') AS DATE) AS day,\n  overall_stress_level\nFROM\n  biathlon_training.stress\nORDER BY date ASC;"
    }
   ]
  },
  {
   "title": "Средна продължитеност на стреса",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT \n  AVG(low_stress_duration) AS low_avg\nFROM biathlon_training.stress\nWHERE date BETWEEN $__timeFrom() AND $__timeTo()"
    },
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT \n  AVG(medium_stress_duration) AS medium_avg\nFROM biathlon_training.stress\nWHERE date BETWEEN $__timeFrom() AND $__timeTo()"
    },
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT \n  AVG(high_stress_duration) AS high_avg\nFROM biathlon_training.stress\nWHERE date BETWEEN $__timeFrom() AND $__timeTo()"
    }
   ]
  },
  {
   "title": "Среден и висок стрес",
   "type": "timeseries",
   "description": "По ден (усреднена стойност за седмица)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  CAST(DATE_FORMAT(date, '%Y-%m-%d 00:00:00') AS DATE) AS day,\n  ROUND(AVG(high_stress_duration) OVER (ORDER BY date ROWS BETWEEN 7 PRECEDING AND CURRENT ROW), 0) AS smoothed_high_stress_duration\nFROM\n  biathlon_training.stress\nORDER BY date ASC;"
    },
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  CAST(DATE_FORMAT(date, '%Y-%m-%d 00:00:00') AS DATE) AS day,\n  ROUND(AVG(medium_stress_duration) OVER (ORDER BY date ROWS BETWEEN 7 PRECEDING AND CURRENT ROW), 0) AS smoothed_medium_stress_duration\nFROM\n  biathlon_training.stress\nORDER BY date ASC;"
    }
   ]
  },
  {
   "title": "Продължителност на стреса по нива",
   "type": "timeseries",
   "description": "По ден (усреднена стойност за седмица)",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  CAST(DATE_FORMAT(date, '%Y-%m-%d 00:00:00') AS DATE) AS day,\n  ROUND(AVG(high_stress_duration) OVER (ORDER BY date ROWS BETWEEN 7 PRECEDING AND CURRENT ROW), 0) AS smoothed_high_stress_duration\nFROM\n  biathlon_training.stress\nORDER BY date ASC;"
    },
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  CAST(DATE_FORMAT(date, '%Y-%m-%d 00:00:00') AS DATE) AS day,\n  ROUND(AVG(medium_stress_duration) OVER (ORDER BY date ROWS BETWEEN 7 PRECEDING AND CURRENT ROW), 0) AS smoothed_medium_stress_duration\nFROM\n  biathlon_training.stress\nORDER BY date ASC;"
    },
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  CAST(DATE_FORMAT(date, '%Y-%m-%d 00:00:00') AS DATE) AS day,\n  ROUND(AVG(low_stress_duration) OVER (ORDER BY date ROWS BETWEEN 7 PRECEDING AND CURRENT ROW), 0) AS smoothed_low_stress_duration\nFROM\n  biathlon_training.stress\nORDER BY date ASC;"
    },
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  CAST(DATE_FORMAT(date, '%Y-%m-%d 00:00:00') AS DATE) AS day,\n  ROUND(AVG(rest_stress_duration) OVER (ORDER BY date ROWS BETWEEN 7 PRECEDING AND CURRENT ROW), 0) AS smoothed_rest_duration\nFROM\n  biathlon_training.stress\nORDER BY date ASC;"
    }
   ]
  },
  {
   "title": "Средно ниво на стрес по година",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  DATE_FORMAT(date, '%Y') AS year,  -- Extract year and month from the date\n  AVG(overall_stress_level) AS avg_overall_stress_level\nFROM\n  biathlon_training.stress\nWHERE\n  date BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY year\nORDER BY year;"
    }
   ]
  },
  {
   "title": "Средно ниво на стрес по месец",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  DATE_FORMAT(date, '%m') AS month,\n  AVG(overall_stress_level) AS avg_overall_stress_level\nFROM\n  biathlon_training.stress\nWHERE\n  date BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY month\nORDER BY month;"
    }
   ]
  },
  {
   "title": "Брой дни с дадено ниво на стрес",
   "type": "barchart",
   "description": "Колко дни съм бил с определено ниво на стрес",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  date,\n  overall_stress_level\nFROM\n  biathlon_training.stress\nWHERE\n  date BETWEEN $__timeFrom() AND $__timeTo() AND \n  overall_stress_level IS NOT NULL\nORDER BY overall_stress_level;"
    }
   ]
  }
 ]
}