{
 "title": "Тегло",
 "time": { "from": "now-8y", "to": "now" },
 "panels": [
  {
   "title": "Текущо тегло",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT weight FROM biathlon_training.weight ORDER BY date DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Промяна",
   "type": "gauge",
   "description": "Средното тегло през последната седмица в сравнение със средното тегло през предходните три седмици.",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$last_week - $previous_3_weeks", "type": "math" }
   ]
  },
  {
   "title": "Тегло",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT \n  CAST(DATE_FORMAT(date, '%Y-%m-%d 00:00:00') AS DATE) AS day,\n  weight\nFROM biathlon_training.weight\nORDER BY date DESC;"
    },
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  CAST(DATE_FORMAT(date, '%Y-%m-%d 00:00:00') AS DATE) AS day,\n  AVG(weight) OVER (ORDER BY date ROWS BETWEEN 7 PRECEDING AND CURRENT ROW) AS smoothed_weight\nFROM\n  biathlon_training.weight\nORDER BY date ASC;"
    }
   ]
  },
  {
   "title": "Средно тегло по месец",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  DATE_FORMAT(date, '%m') AS month,\n  AVG(weight) AS avg_weight\nFROM\n  biathlon_training.weight\nWHERE\n  date BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY month\nORDER BY month;"
    }
   ]
  },
  {
   "title": "Брой дни с дадено тегло",
   "type": "barchart",
   "description": "Колко дни съм бил на определени килограми",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  date,\n  ROUND(weight) AS int_weight\nFROM\n  biathlon_training.weight\nWHERE\n  date BETWEEN $__timeFrom() AND $__timeTo()\nORDER BY int_weight;"
    }
   ]
  },
  {
   "title": "Средно тегло по година",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "dataset": "biathlon_training",
     "rawSql": "SELECT\n  DATE_FORMAT(date, '%Y') AS year,  -- Extract year and month from the date\n  AVG(weight) AS avg_weight              -- Calculate average weight for each month\nFROM\n  biathlon_training.weight\nWHERE\n  date BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY year                           -- Group by the extracted month\nORDER BY year;"
    }
   ]
  }
 ]
}